version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.10.5-alpine
    restart: on-failure
    ports:
      - ${RMQ_PORT}:${RMQ_PORT}

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/test:/usr/src/app/test    
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - rabbitmq

  ocr-service:
    build:
      context: ./ocr-service
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./ocr-service/src:/usr/src/app/src
      - ./ocr-service/test:/usr/src/app/test    
    ports:
      - ${OCR_SERVICE_PORT}:${OCR_SERVICE_PORT}
    depends_on:
      - rabbitmq